### ISSUE TITLE
错误item问题

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/NukkitPetteriM1Edition#37]
使用指令给予没有注册的物品，例如id为:1145的物品
获取后，将它放置于地图，客户端会崩溃，服务端报错
服务端版本(通过/ver获取):
 ###############################################
 Nukkit-PM1E-MOT
 Build: master/0298139
 Multiversion: Up to version 1.19.63
 ###############################################
 [Nukkit-PM1E-MOT] You are running the latest version.
报错如下：
2023-03-11 08:39:21.971 [Batching Executor] ERROR - Throwing
java.lang.IllegalArgumentException: Unknown legacy2Runtime mapping: id=1145 meta=0
	at cn.nukkit.item.RuntimeItemMapping.toRuntime(RuntimeItemMapping.java:181) ~[server.jar:?]
	at cn.nukkit.utils.BinaryStream.putSlotNew(BinaryStream.java:924) ~[server.jar:?]
	at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:733) ~[server.jar:?]
	at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:728) ~[server.jar:?]
	at cn.nukkit.network.protocol.MobEquipmentPacket.encode(MobEquipmentPacket.java:39) ~[server.jar:?]
	at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:96) ~[server.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.sendPacket(RakNetPlayerSession.java:109) ~[server.jar:?]
	at cn.nukkit.network.BatchingHelper.batchAndSendPackets(BatchingHelper.java:53) ~[server.jar:?]
	at cn.nukkit.network.BatchingHelper.lambda$batchPackets$0(BatchingHelper.java:43) ~[server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by lt-name** [comment]
无法复现崩端情况，核心存在错误物品替换机制，会报错但是会作为更新方块处理
