### ISSUE TITLE
FakeInventories plugin not working on PM1E incase of there's no runtime id for chest(I think so)

### ISSUE THREAD

**Issue by KoshakMineDEV** [MemoriesOfTime/NukkitPetteriM1Edition#50]
When I'm trying to open Custom inventory to player i got error ```Tried to get block runtime id for unsupported protocol version: 54```
FakeInventories plugin: https://cloudburstmc.org/resources/fakeinventories.837/
This is not FakeInventories or my issue, everything works fine on PowerNukkitX
Stacktrace i got:
```Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3309) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:162) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:115) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1331) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1076) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:1044) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:761) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:82) [Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
Caused by: java.lang.IllegalArgumentException: Tried to get block runtime id for unsupported protocol version: 54
        at cn.nukkit.level.GlobalBlockPalette.getOrCreateRuntimeId(GlobalBlockPalette.java:632) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at me.iwareq.fakeinventories.block.SingleFakeBlock.lambda$create$0(SingleFakeBlock.java:34) ~[?:?]
        at java.util.Collections$SingletonList.forEach(Collections.java:4966) ~[?:?]
        at me.iwareq.fakeinventories.block.SingleFakeBlock.create(SingleFakeBlock.java:32) ~[?:?]
        at me.iwareq.fakeinventories.CustomInventory.onOpen(CustomInventory.java:38) ~[?:?]
        at cn.nukkit.inventory.BaseInventory.open(BaseInventory.java:443) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.addWindow(Player.java:5811) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.addWindow(Player.java:5792) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.addWindow(Player.java:5788) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.addWindow(Player.java:5784) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        at com.clubdev.seller.SellCommand.sendBuyingUI(SellCommand.java:41) ~[?:?]
        at com.clubdev.seller.SellCommand.lambda$sendMainForm$0(SellCommand.java:31) ~[?:?]
        at ru.contentforge.formconstructor.form.response.SimpleFormResponse.handle(SimpleFormResponse.java:20) ~[?:?]
        at ru.contentforge.formconstructor.task.FormHandlingTask.onRun(FormHandlingTask.java:39) ~[?:?]
        at ru.contentforge.formconstructor.FormConstructor.onFormResponded(FormConstructor.java:30) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[Nukkit-PM1E-MOT-SNAPSHOT.jar:?]
        ```

**Comment by BlusteryS** [comment]
https://github.com/PetteriM1/FakeInventories

Try this plugin

**Comment by lt-name** [comment]
We maintain compatibility with Nukkit-PM1E as much as possible, so some plugins running on nkx may have problems, and some plugins need to use a modified version for PM1E

**Comment by lt-name** [comment]
If you have further questions you can reopen the pr
